name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3307:3306
        env:
          MYSQL_ROOT_PASSWORD: Loan@1456
          MYSQL_DATABASE: web_application

    steps:
      - name : Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Set up Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build Docker containers
        run: |
          docker-compose -f docker-compose.yml build

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/myapp:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/myapp:latest
      - name: Add server to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H 127.0.0.1 >> ~/.ssh/known_hosts

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to server
        run: |
          ssh quynhloan@127.0.0.1 'docker pull ${{ secrets.DOCKERHUB_USERNAME }}/myapp:latest && docker-compose up -d'

      - name: Run migrations
        run: |
          docker-compose -f docker-compose.yml run web python manage.py migrate

      - name: Run tests
        run: |
          docker-compose -f docker-compose.yml run web python manage.py test
#      - name: Build the Docker image
#          run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
#
#  deploy:
#    needs: build
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v2
#
#      - name: Set up Docker Compose
#        run: |
#          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
#          sudo chmod +x /usr/local/bin/docker-compose
#
#      - name: Build and push Docker image
#        run: |
#          docker build -t your-dockerhub-username/your-app-name .
#          echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
#          docker push your-dockerhub-username/your-app-name
#
#      - name: Deploy to server
#        run: |
#          ssh -o StrictHostKeyChecking=no your-user@your-server "docker pull your-dockerhub-username/your-app-name && docker-compose up -d"
#
